
package telas;

import Classes.Agendamento;

public class agendamentoConsultasConsultar extends javax.swing.JFrame {

    /**
     * Creates new form agendamentoConsultas
     */
    public agendamentoConsultasConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        WhitePanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        frmtNumero = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEspecialidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMedico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        frmtData = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtUnidade = new javax.swing.JTextField();
        btnControlePacientes = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        frmtHora = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agendamento de Consultas");

        jPanel2.setBackground(new java.awt.Color(1, 28, 102));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1112, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(1576, 24, 1112, 859);

        WhitePanel.setBackground(new java.awt.Color(255, 255, 255));
        WhitePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        WhitePanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                WhitePanelFocusGained(evt);
            }
        });
        WhitePanel.setLayout(null);

        jButton2.setBackground(new java.awt.Color(203, 39, 61));
        jButton2.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jButton2.setText("Fechar Consulta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        WhitePanel.add(jButton2);
        jButton2.setBounds(850, 500, 160, 29);

        jLabel11.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(203, 39, 61));
        jLabel11.setText("Nome do Paciente");
        WhitePanel.add(jLabel11);
        jLabel11.setBounds(40, 130, 270, 20);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        WhitePanel.add(txtNome);
        txtNome.setBounds(30, 150, 460, 40);

        jLabel6.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(203, 39, 61));
        jLabel6.setText("Numero de Telefone");
        WhitePanel.add(jLabel6);
        jLabel6.setBounds(40, 220, 210, 20);

        try {
            frmtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        WhitePanel.add(frmtNumero);
        frmtNumero.setBounds(30, 240, 460, 40);

        jLabel12.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(203, 39, 61));
        jLabel12.setText("Especialidade Médica");
        WhitePanel.add(jLabel12);
        jLabel12.setBounds(40, 310, 270, 20);

        txtEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecialidadeActionPerformed(evt);
            }
        });
        WhitePanel.add(txtEspecialidade);
        txtEspecialidade.setBounds(30, 330, 460, 40);

        jLabel10.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(203, 39, 61));
        jLabel10.setText("Médico Responsável");
        WhitePanel.add(jLabel10);
        jLabel10.setBounds(40, 410, 240, 20);

        txtMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicoActionPerformed(evt);
            }
        });
        WhitePanel.add(txtMedico);
        txtMedico.setBounds(30, 430, 460, 40);

        jLabel3.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(203, 39, 61));
        jLabel3.setText("Data da Consulta");
        WhitePanel.add(jLabel3);
        jLabel3.setBounds(570, 130, 280, 20);

        try {
            frmtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        WhitePanel.add(frmtData);
        frmtData.setBounds(560, 150, 460, 40);

        jLabel13.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(203, 39, 61));
        jLabel13.setText("Tipo de Consulta");
        WhitePanel.add(jLabel13);
        jLabel13.setBounds(570, 310, 240, 20);

        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });
        WhitePanel.add(txtType);
        txtType.setBounds(560, 330, 460, 40);

        jLabel14.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(203, 39, 61));
        jLabel14.setText("Unidade de Atendimento");
        WhitePanel.add(jLabel14);
        jLabel14.setBounds(570, 410, 300, 20);

        txtUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadeActionPerformed(evt);
            }
        });
        WhitePanel.add(txtUnidade);
        txtUnidade.setBounds(560, 430, 460, 40);

        btnControlePacientes.setBackground(new java.awt.Color(255, 255, 255));
        btnControlePacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/e-healthLogo.png"))); // NOI18N
        btnControlePacientes.setBorder(null);
        btnControlePacientes.setBorderPainted(false);
        btnControlePacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnControlePacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlePacientesActionPerformed(evt);
            }
        });
        WhitePanel.add(btnControlePacientes);
        btnControlePacientes.setBounds(30, 10, 80, 100);

        jLabel4.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(203, 39, 61));
        jLabel4.setText("Hora da Consulta");
        WhitePanel.add(jLabel4);
        jLabel4.setBounds(570, 220, 280, 20);

        try {
            frmtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        frmtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmtHoraActionPerformed(evt);
            }
        });
        WhitePanel.add(frmtHora);
        frmtHora.setBounds(560, 240, 460, 40);

        jButton3.setBackground(new java.awt.Color(203, 39, 61));
        jButton3.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        WhitePanel.add(jButton3);
        jButton3.setBounds(730, 500, 120, 29);

        jPanel2.add(WhitePanel);
        WhitePanel.setBounds(10, 10, 1060, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WhitePanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WhitePanelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_WhitePanelFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecialidadeActionPerformed

    private void txtMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicoActionPerformed

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void txtUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadeActionPerformed

    private void btnControlePacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlePacientesActionPerformed
        // TODO add your handling code here:

        index lgn = new index();
        lgn.show();
        this.dispose();
    }//GEN-LAST:event_btnControlePacientesActionPerformed

    private void frmtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frmtHoraActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        optionAgendamento opt = new optionAgendamento();
        opt.show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agendamentoConsultasConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agendamentoConsultasConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agendamentoConsultasConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agendamentoConsultasConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agendamentoConsultasConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WhitePanel;
    private javax.swing.JButton btnControlePacientes;
    private javax.swing.JFormattedTextField frmtData;
    private javax.swing.JFormattedTextField frmtHora;
    private javax.swing.JFormattedTextField frmtNumero;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtEspecialidade;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtUnidade;
    // End of variables declaration//GEN-END:variables

        public void setText(String nome, String numero, String especialidade, String medic, String data, String hora, String type, String unidade) {
            txtNome.setText(nome);
            frmtNumero.setText(numero);
            txtEspecialidade.setText(especialidade);
            txtMedico.setText(medic);
            frmtData.setText(data);
            frmtHora.setText(hora);
            txtType.setText(type);
            txtUnidade.setText(unidade);
    }
    

    


}
