
package telas;


public class index extends javax.swing.JFrame {

    /**
     * Creates new form esqueceuSenha
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eHealthLogo = new javax.swing.JLabel();
        eHealthText = new javax.swing.JLabel();
        eHealthText1 = new javax.swing.JLabel();
        eHealthLogo1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        WhitePanel = new javax.swing.JPanel();
        btnAgendamentoConsultas = new javax.swing.JButton();
        btnControlePacientes = new javax.swing.JButton();
        btnRegistroConsultas = new javax.swing.JButton();
        btnGestaoExames = new javax.swing.JButton();
        lblGestaoExames = new javax.swing.JLabel();
        lblControlePacientes = new javax.swing.JLabel();
        lblAgendamentoConsultas = new javax.swing.JLabel();
        lblRegistroConsultas = new javax.swing.JLabel();
        eHealthText2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        eHealthLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/e-healthLogo.png"))); // NOI18N

        eHealthText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eHtxt.png"))); // NOI18N

        eHealthText1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eHtxt.png"))); // NOI18N

        eHealthLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/e-healthLogo.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setSize(new java.awt.Dimension(800, 800));

        jPanel2.setBackground(new java.awt.Color(1, 28, 102));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1112, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(1576, 24, 1112, 859);

        WhitePanel.setBackground(new java.awt.Color(255, 255, 255));
        WhitePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        WhitePanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                WhitePanelFocusGained(evt);
            }
        });
        WhitePanel.setLayout(null);

        btnAgendamentoConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon.png"))); // NOI18N
        btnAgendamentoConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendamentoConsultasActionPerformed(evt);
            }
        });
        WhitePanel.add(btnAgendamentoConsultas);
        btnAgendamentoConsultas.setBounds(800, 210, 240, 230);

        btnControlePacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconControle.png"))); // NOI18N
        btnControlePacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlePacientesActionPerformed(evt);
            }
        });
        WhitePanel.add(btnControlePacientes);
        btnControlePacientes.setBounds(20, 210, 240, 230);

        btnRegistroConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/patient-consulting-with-a-medical-professional.png"))); // NOI18N
        btnRegistroConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroConsultasActionPerformed(evt);
            }
        });
        WhitePanel.add(btnRegistroConsultas);
        btnRegistroConsultas.setBounds(280, 210, 240, 230);

        btnGestaoExames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconGestao.png"))); // NOI18N
        btnGestaoExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestaoExamesActionPerformed(evt);
            }
        });
        WhitePanel.add(btnGestaoExames);
        btnGestaoExames.setBounds(540, 210, 240, 230);

        lblGestaoExames.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblGestaoExames.setForeground(new java.awt.Color(203, 39, 61));
        lblGestaoExames.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestaoExames.setText("Registro de Exames");
        WhitePanel.add(lblGestaoExames);
        lblGestaoExames.setBounds(540, 450, 240, 20);

        lblControlePacientes.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblControlePacientes.setForeground(new java.awt.Color(203, 39, 61));
        lblControlePacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblControlePacientes.setText("Controle de Pacientes");
        WhitePanel.add(lblControlePacientes);
        lblControlePacientes.setBounds(21, 450, 240, 20);

        lblAgendamentoConsultas.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblAgendamentoConsultas.setForeground(new java.awt.Color(203, 39, 61));
        lblAgendamentoConsultas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgendamentoConsultas.setText("Agendamentos");
        WhitePanel.add(lblAgendamentoConsultas);
        lblAgendamentoConsultas.setBounds(790, 450, 270, 24);

        lblRegistroConsultas.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblRegistroConsultas.setForeground(new java.awt.Color(203, 39, 61));
        lblRegistroConsultas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistroConsultas.setText("Registro de Consultas");
        WhitePanel.add(lblRegistroConsultas);
        lblRegistroConsultas.setBounds(280, 450, 240, 20);

        eHealthText2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eHtxt.png"))); // NOI18N
        WhitePanel.add(eHealthText2);
        eHealthText2.setBounds(300, -130, 480, 340);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/e-healthLogo.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        WhitePanel.add(jButton1);
        jButton1.setBounds(330, 60, 100, 110);

        jPanel2.add(WhitePanel);
        WhitePanel.setBounds(10, 10, 1060, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1096, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WhitePanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WhitePanelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_WhitePanelFocusGained

    private void btnControlePacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlePacientesActionPerformed
        // TODO add your handling code here:
        optionControle optCntrl = new optionControle();
        optCntrl.show();
        this.dispose();

    }//GEN-LAST:event_btnControlePacientesActionPerformed

    private void btnRegistroConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroConsultasActionPerformed
        // TODO add your handling code here:
        optionRegistro optRegistro = new optionRegistro();
        optRegistro.show();
        this.dispose();
        
        
    }//GEN-LAST:event_btnRegistroConsultasActionPerformed

    private void btnGestaoExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestaoExamesActionPerformed
        // TODO add your handling code here:
        optionExames optExame = new optionExames();
        optExame.show();
        this.dispose();
        
    }//GEN-LAST:event_btnGestaoExamesActionPerformed

    private void btnAgendamentoConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendamentoConsultasActionPerformed
        // TODO add your handling code here:
        optionAgendamento agndmnt = new optionAgendamento();
        agndmnt.show();
        this.dispose();

    }//GEN-LAST:event_btnAgendamentoConsultasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        login lgn = new login();
        lgn.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WhitePanel;
    private javax.swing.JButton btnAgendamentoConsultas;
    private javax.swing.JButton btnControlePacientes;
    private javax.swing.JButton btnGestaoExames;
    private javax.swing.JButton btnRegistroConsultas;
    private javax.swing.JLabel eHealthLogo;
    private javax.swing.JLabel eHealthLogo1;
    private javax.swing.JLabel eHealthText;
    private javax.swing.JLabel eHealthText1;
    private javax.swing.JLabel eHealthText2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAgendamentoConsultas;
    private javax.swing.JLabel lblControlePacientes;
    private javax.swing.JLabel lblGestaoExames;
    private javax.swing.JLabel lblRegistroConsultas;
    // End of variables declaration//GEN-END:variables
}
