
package telas;

import Classes.Funcionario;
import Classes.UsuarioLogado;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        WhitePanel = new javax.swing.JPanel();
        lblSubtitulo = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        ckSenha = new javax.swing.JCheckBox();
        txtSenha = new javax.swing.JPasswordField();
        ckRemeberMe = new javax.swing.JCheckBox();
        btnForgotPassword = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblRegister = new javax.swing.JLabel();
        btnCreateAccount = new javax.swing.JButton();
        purplePanel = new javax.swing.JPanel();
        lblLotus = new javax.swing.JLabel();
        eHealthLogo = new javax.swing.JLabel();
        eHealthText = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setSize(new java.awt.Dimension(1080, 549));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(1, 28, 102));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1112, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(1576, 24, 1112, 859);

        WhitePanel.setBackground(new java.awt.Color(255, 255, 255));
        WhitePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        WhitePanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                WhitePanelFocusGained(evt);
            }
        });
        WhitePanel.setLayout(null);

        lblSubtitulo.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(5, 130, 132));
        lblSubtitulo.setText("E veja o que está acontecendo com a sua Saúde");
        WhitePanel.add(lblSubtitulo);
        lblSubtitulo.setBounds(620, 160, 340, 20);

        lblSenha.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(122, 25, 182));
        lblSenha.setText("Senha");
        WhitePanel.add(lblSenha);
        lblSenha.setBounds(640, 270, 140, 20);

        lblUser.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(122, 25, 182));
        lblUser.setText("Usuário");
        WhitePanel.add(lblUser);
        lblUser.setBounds(640, 210, 150, 20);

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        WhitePanel.add(txtEmail);
        txtEmail.setBounds(620, 230, 340, 28);

        ckSenha.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        ckSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-closed-eye-64.png"))); // NOI18N
        ckSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSenhaActionPerformed(evt);
            }
        });
        WhitePanel.add(ckSenha);
        ckSenha.setBounds(930, 290, 30, 30);

        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
        });
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        WhitePanel.add(txtSenha);
        txtSenha.setBounds(620, 290, 340, 28);

        ckRemeberMe.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        ckRemeberMe.setForeground(new java.awt.Color(205, 55, 212));
        ckRemeberMe.setText("Salvar Login");
        WhitePanel.add(ckRemeberMe);
        ckRemeberMe.setBounds(630, 320, 130, 18);

        btnForgotPassword.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        btnForgotPassword.setForeground(new java.awt.Color(205, 55, 212));
        btnForgotPassword.setText("Esqueceu sua Senha?");
        btnForgotPassword.setBorder(null);
        btnForgotPassword.setBorderPainted(false);
        btnForgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotPasswordActionPerformed(evt);
            }
        });
        WhitePanel.add(btnForgotPassword);
        btnForgotPassword.setBounds(790, 320, 170, 20);

        btnLogin.setBackground(new java.awt.Color(53, 47, 143));
        btnLogin.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        WhitePanel.add(btnLogin);
        btnLogin.setBounds(620, 370, 340, 50);

        lblRegister.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(122, 25, 182));
        lblRegister.setText("Ainda não está Registrado?");
        WhitePanel.add(lblRegister);
        lblRegister.setBounds(640, 480, 250, 30);

        btnCreateAccount.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        btnCreateAccount.setForeground(new java.awt.Color(205, 55, 212));
        btnCreateAccount.setText("Crie Uma Conta");
        btnCreateAccount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        WhitePanel.add(btnCreateAccount);
        btnCreateAccount.setBounds(630, 480, 330, 29);

        purplePanel.setBackground(new java.awt.Color(61, 17, 111));

        lblLotus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lotus-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout purplePanelLayout = new javax.swing.GroupLayout(purplePanel);
        purplePanel.setLayout(purplePanelLayout);
        purplePanelLayout.setHorizontalGroup(
            purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purplePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLotus, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        purplePanelLayout.setVerticalGroup(
            purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purplePanelLayout.createSequentialGroup()
                .addComponent(lblLotus, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        WhitePanel.add(purplePanel);
        purplePanel.setBounds(10, 10, 540, 520);

        eHealthLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/e-healthLogo.png"))); // NOI18N
        WhitePanel.add(eHealthLogo);
        eHealthLogo.setBounds(620, 30, 80, 90);

        eHealthText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eHtxt.png"))); // NOI18N
        WhitePanel.add(eHealthText);
        eHealthText.setBounds(580, -160, 480, 340);

        lblTitulo1.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(5, 130, 132));
        lblTitulo1.setText("Faça Login na Sua Conta");
        WhitePanel.add(lblTitulo1);
        lblTitulo1.setBounds(620, 140, 270, 30);

        jPanel2.add(WhitePanel);
        WhitePanel.setBounds(10, 10, 1060, 540);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1080, 560);

        setSize(new java.awt.Dimension(1096, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        Funcionario func = new Funcionario();
        func.setUsuario(txtEmail.getText());
        func.setSenha(txtSenha.getText());
        
        boolean teste = func.Login();
        System.out.println("teste - " + teste);
        
        
        if(teste)
        {
            
            if (func.LoginComAdm()) {
    UsuarioLogado.setAdministrador(true);
} else {
    UsuarioLogado.setAdministrador(false);
}
            JOptionPane.showMessageDialog(null, "Login Efetuado Com Sucesso, Seja Bem Vindo " + txtEmail.getText());
            index inicial = new index();
            inicial.show();
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Login ou Senha Invalidos");   

        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here: cadastrar
        
        isAdm confirm = new isAdm();
        JOptionPane.showMessageDialog(null, "Essa Ação Requere Permissão de Administrador");
        confirm.show();
        this.dispose();
        
        
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEmailFocusGained

    private void btnForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotPasswordActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_btnForgotPasswordActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSenhaFocusGained

    private void WhitePanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WhitePanelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_WhitePanelFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        txtEmail.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void ckSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSenhaActionPerformed
        // TODO add your handling code here:

        if (ckSenha.isSelected()) {
            txtSenha.setEchoChar((char)0);
            ckSenha.setIcon(new ImageIcon(getClass().getResource("/img/icons8-eye-64.png")));
        }else{
            txtSenha.setEchoChar('*');
            ckSenha.setIcon(new ImageIcon(getClass().getResource("/img/icons8-closed-eye-64.png")));
        }
    }//GEN-LAST:event_ckSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WhitePanel;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnForgotPassword;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox ckRemeberMe;
    private javax.swing.JCheckBox ckSenha;
    private javax.swing.JLabel eHealthLogo;
    private javax.swing.JLabel eHealthText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLotus;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel purplePanel;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
