
package telas;

import Classes.Agendamento;
import Classes.Pacientes;
import java.util.List;
import javax.swing.JOptionPane;

public class optionAgendamento extends javax.swing.JFrame {

    /**
     * Creates new form esqueceuSenha
     */
    public optionAgendamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eHealthLogo = new javax.swing.JLabel();
        eHealthText = new javax.swing.JLabel();
        eHealthText1 = new javax.swing.JLabel();
        eHealthLogo1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        WhitePanel = new javax.swing.JPanel();
        btnControlePacientes = new javax.swing.JButton();
        lblControlePacientes = new javax.swing.JLabel();
        eHealthLogo2 = new javax.swing.JLabel();
        eHealthText2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnControlePacientes1 = new javax.swing.JButton();
        lblControlePacientes1 = new javax.swing.JLabel();

        eHealthLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/e-healthLogo.png"))); // NOI18N

        eHealthText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eHtxt.png"))); // NOI18N

        eHealthText1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eHtxt.png"))); // NOI18N

        eHealthLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/e-healthLogo.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("O que Deseja Fazer?");
        setSize(new java.awt.Dimension(800, 800));

        jPanel2.setBackground(new java.awt.Color(1, 28, 102));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1112, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(1576, 24, 1112, 859);

        WhitePanel.setBackground(new java.awt.Color(255, 255, 255));
        WhitePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        WhitePanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                WhitePanelFocusGained(evt);
            }
        });
        WhitePanel.setLayout(null);

        btnControlePacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/0icons8-add-64.png"))); // NOI18N
        btnControlePacientes.setBorder(null);
        btnControlePacientes.setBorderPainted(false);
        btnControlePacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlePacientesActionPerformed(evt);
            }
        });
        WhitePanel.add(btnControlePacientes);
        btnControlePacientes.setBounds(550, 170, 240, 230);

        lblControlePacientes.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblControlePacientes.setForeground(new java.awt.Color(203, 39, 61));
        lblControlePacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblControlePacientes.setText("Agendar");
        WhitePanel.add(lblControlePacientes);
        lblControlePacientes.setBounds(550, 410, 240, 30);

        eHealthLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/e-healthLogo.png"))); // NOI18N
        WhitePanel.add(eHealthLogo2);
        eHealthLogo2.setBounds(340, 60, 80, 90);

        eHealthText2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eHtxt.png"))); // NOI18N
        WhitePanel.add(eHealthText2);
        eHealthText2.setBounds(300, -140, 480, 340);

        jButton2.setBackground(new java.awt.Color(203, 39, 61));
        jButton2.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        WhitePanel.add(jButton2);
        jButton2.setBounds(920, 490, 120, 29);

        btnControlePacientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-calendar-96.png"))); // NOI18N
        btnControlePacientes1.setBorder(null);
        btnControlePacientes1.setBorderPainted(false);
        btnControlePacientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlePacientes1ActionPerformed(evt);
            }
        });
        WhitePanel.add(btnControlePacientes1);
        btnControlePacientes1.setBounds(230, 170, 240, 230);

        lblControlePacientes1.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblControlePacientes1.setForeground(new java.awt.Color(203, 39, 61));
        lblControlePacientes1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblControlePacientes1.setText("Abrir Agenda");
        WhitePanel.add(lblControlePacientes1);
        lblControlePacientes1.setBounds(230, 410, 240, 30);

        jPanel2.add(WhitePanel);
        WhitePanel.setBounds(10, 10, 1060, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1096, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WhitePanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WhitePanelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_WhitePanelFocusGained

    private void btnControlePacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlePacientesActionPerformed
        // TODO add your handling code here:
        agendamentoConsultas agndmnt = new agendamentoConsultas();
        agndmnt.show();
        this.dispose();

    }//GEN-LAST:event_btnControlePacientesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        index inicial = new index();
        inicial.show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
 
    private void btnControlePacientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlePacientes1ActionPerformed
        // TODO add your handling code here:
        
        String cpfPaciente = JOptionPane.showInputDialog(null, "Insira a Data que Deseja Consultar: ");

                 this.dispose();
        
         Agendamento tstConsulta = new Agendamento();
         tstConsulta.buscarPorDataConsultar(cpfPaciente);
         

         
         

    }//GEN-LAST:event_btnControlePacientes1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(optionAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(optionAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(optionAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(optionAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new optionAgendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WhitePanel;
    private javax.swing.JButton btnControlePacientes;
    private javax.swing.JButton btnControlePacientes1;
    private javax.swing.JLabel eHealthLogo;
    private javax.swing.JLabel eHealthLogo1;
    private javax.swing.JLabel eHealthLogo2;
    private javax.swing.JLabel eHealthText;
    private javax.swing.JLabel eHealthText1;
    private javax.swing.JLabel eHealthText2;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblControlePacientes;
    private javax.swing.JLabel lblControlePacientes1;
    // End of variables declaration//GEN-END:variables
}
