
package telas;

import Classes.Pacientes;
import Classes.UsuarioLogado;
import javax.swing.JOptionPane;


public class optionControle extends javax.swing.JFrame {

    /**
     * Creates new form esqueceuSenha
     */
    public optionControle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eHealthLogo = new javax.swing.JLabel();
        eHealthText = new javax.swing.JLabel();
        eHealthText1 = new javax.swing.JLabel();
        eHealthLogo1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        WhitePanel = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        btnControlePacientes = new javax.swing.JButton();
        btnRegistroConsultas = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        lblGestaoExames = new javax.swing.JLabel();
        lblControlePacientes = new javax.swing.JLabel();
        lblAgendamentoConsultas = new javax.swing.JLabel();
        lblRegistroConsultas = new javax.swing.JLabel();
        eHealthLogo2 = new javax.swing.JLabel();
        eHealthText2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        eHealthLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/e-healthLogo.png"))); // NOI18N

        eHealthText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eHtxt.png"))); // NOI18N

        eHealthText1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eHtxt.png"))); // NOI18N

        eHealthLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/e-healthLogo.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("O que Deseja Fazer?");
        setSize(new java.awt.Dimension(800, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(1, 28, 102));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1112, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(1576, 24, 1112, 859);

        WhitePanel.setBackground(new java.awt.Color(255, 255, 255));
        WhitePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        WhitePanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                WhitePanelFocusGained(evt);
            }
        });
        WhitePanel.setLayout(null);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4icons8-remove-64.png"))); // NOI18N
        btnExcluir.setBorder(null);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        WhitePanel.add(btnExcluir);
        btnExcluir.setBounds(800, 180, 240, 230);

        btnControlePacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/0icons8-add-64.png"))); // NOI18N
        btnControlePacientes.setBorder(null);
        btnControlePacientes.setBorderPainted(false);
        btnControlePacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlePacientesActionPerformed(evt);
            }
        });
        WhitePanel.add(btnControlePacientes);
        btnControlePacientes.setBounds(20, 180, 240, 230);

        btnRegistroConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2icons8-search-database-50.png"))); // NOI18N
        btnRegistroConsultas.setBorder(null);
        btnRegistroConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroConsultasActionPerformed(evt);
            }
        });
        WhitePanel.add(btnRegistroConsultas);
        btnRegistroConsultas.setBounds(280, 180, 240, 230);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3icons8-update-50.png"))); // NOI18N
        btnAlterar.setBorder(null);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        WhitePanel.add(btnAlterar);
        btnAlterar.setBounds(540, 180, 240, 230);

        lblGestaoExames.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblGestaoExames.setForeground(new java.awt.Color(203, 39, 61));
        lblGestaoExames.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestaoExames.setText("Alterar Registro");
        WhitePanel.add(lblGestaoExames);
        lblGestaoExames.setBounds(540, 420, 240, 20);

        lblControlePacientes.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblControlePacientes.setForeground(new java.awt.Color(203, 39, 61));
        lblControlePacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblControlePacientes.setText("Criar Novo");
        WhitePanel.add(lblControlePacientes);
        lblControlePacientes.setBounds(20, 420, 240, 20);

        lblAgendamentoConsultas.setFont(new java.awt.Font("Snap ITC", 0, 16)); // NOI18N
        lblAgendamentoConsultas.setForeground(new java.awt.Color(203, 39, 61));
        lblAgendamentoConsultas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgendamentoConsultas.setText("Excluir Registro");
        WhitePanel.add(lblAgendamentoConsultas);
        lblAgendamentoConsultas.setBounds(790, 420, 270, 20);

        lblRegistroConsultas.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        lblRegistroConsultas.setForeground(new java.awt.Color(203, 39, 61));
        lblRegistroConsultas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistroConsultas.setText("Consultar Registro");
        WhitePanel.add(lblRegistroConsultas);
        lblRegistroConsultas.setBounds(280, 420, 240, 20);

        eHealthLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/e-healthLogo.png"))); // NOI18N
        WhitePanel.add(eHealthLogo2);
        eHealthLogo2.setBounds(340, 60, 80, 90);

        eHealthText2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eHtxt.png"))); // NOI18N
        WhitePanel.add(eHealthText2);
        eHealthText2.setBounds(300, -140, 480, 340);

        jButton2.setBackground(new java.awt.Color(203, 39, 61));
        jButton2.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        WhitePanel.add(jButton2);
        jButton2.setBounds(920, 490, 120, 24);

        jPanel2.add(WhitePanel);
        WhitePanel.setBounds(10, 10, 1060, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1096, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WhitePanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WhitePanelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_WhitePanelFocusGained

    private void btnControlePacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlePacientesActionPerformed
        // TODO add your handling code here:
        controlePacientes cntrl = new controlePacientes();
        cntrl.show();
        this.dispose();

    }//GEN-LAST:event_btnControlePacientesActionPerformed

    private void btnRegistroConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroConsultasActionPerformed
        // TODO add your handling code here:
       
        
        String cpfPaciente = JOptionPane.showInputDialog(null, "Insira o CPF do Paciente Que deseja Consultar(Ex:000.000.000-00): ");
        
         Pacientes tstConsulta = new Pacientes();
         tstConsulta.buscarPorCPFConsultar(cpfPaciente);
         
         
       
        this.dispose();
        
        
        

//        if ("777".equals(cpfPaciente) ) {
//            cntrl.setText("Gustavo de Cassio Gomes Perez", "26112004","49231267877", "Rua da Agua", "11952658821", "gustavodecassio00@gmail.com");
//            cntrl.desabilitarCampos();
//            cntrl.show();
//            this.dispose();
//        }else{
//            JOptionPane.showMessageDialog(null,"Paciente nao Cadastrado");
//        }
        

        

        
        
    }//GEN-LAST:event_btnRegistroConsultasActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        
        String cpfPaciente = JOptionPane.showInputDialog(null, 
                "Insira o CPF do Paciente que Deseja Alterar: ");
        
         Pacientes tstConsulta = new Pacientes();
         tstConsulta.buscarPorCPFAlterar(cpfPaciente);
         
//        controlePacientes cntrl = new controlePacientes();
//        cntrl.show();
//        this.dispose();
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        String cpfPaciente = JOptionPane.showInputDialog(null, 
                "Insira o CPF do Paciente que Deseja Alterar: ");
        
         Pacientes tstExcluir = new Pacientes();
         tstExcluir.buscarPorCPFExcluir(cpfPaciente);
          
//        controlePacientes cntrl = new controlePacientes();
//        cntrl.show();
//        this.dispose();

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        index inicial = new index();
        inicial.show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here: abriu a janela
        
        if (!UsuarioLogado.isAdministrador()) {
    btnAlterar.setEnabled(false);
    btnExcluir.setEnabled(false);
}
       
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(optionControle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(optionControle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(optionControle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(optionControle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new optionControle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WhitePanel;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnControlePacientes;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnRegistroConsultas;
    private javax.swing.JLabel eHealthLogo;
    private javax.swing.JLabel eHealthLogo1;
    private javax.swing.JLabel eHealthLogo2;
    private javax.swing.JLabel eHealthText;
    private javax.swing.JLabel eHealthText1;
    private javax.swing.JLabel eHealthText2;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAgendamentoConsultas;
    private javax.swing.JLabel lblControlePacientes;
    private javax.swing.JLabel lblGestaoExames;
    private javax.swing.JLabel lblRegistroConsultas;
    // End of variables declaration//GEN-END:variables
}
