
package telas;

import Classes.Consultas;
import javax.swing.JOptionPane;


public class registroConsultasExcluir extends javax.swing.JFrame {

    /**
     * Creates new form registroConsultas
     */
    public registroConsultasExcluir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        WhitePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtConsPacient = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtConsData = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtConsMedic = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtConsObs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        fileProntuario = new javax.swing.JFileChooser();
        txtConsType = new javax.swing.JTextField();
        txtConsStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Consultas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(1, 28, 102));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1112, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(1576, 24, 1112, 859);

        WhitePanel.setBackground(new java.awt.Color(255, 255, 255));
        WhitePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        WhitePanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                WhitePanelFocusGained(evt);
            }
        });
        WhitePanel.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(203, 39, 61));
        jLabel9.setText("Paciente");
        WhitePanel.add(jLabel9);
        jLabel9.setBounds(30, 20, 150, 20);

        txtConsPacient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsPacientActionPerformed(evt);
            }
        });
        WhitePanel.add(txtConsPacient);
        txtConsPacient.setBounds(20, 40, 460, 30);

        jLabel3.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(203, 39, 61));
        jLabel3.setText("Data e Hora da Consulta");
        WhitePanel.add(jLabel3);
        jLabel3.setBounds(30, 80, 280, 20);

        try {
            txtConsData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####   ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        WhitePanel.add(txtConsData);
        txtConsData.setBounds(20, 100, 460, 30);

        jLabel10.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(203, 39, 61));
        jLabel10.setText("Médico Responsável");
        WhitePanel.add(jLabel10);
        jLabel10.setBounds(30, 140, 240, 20);

        txtConsMedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsMedicActionPerformed(evt);
            }
        });
        WhitePanel.add(txtConsMedic);
        txtConsMedic.setBounds(20, 160, 460, 30);

        jLabel2.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(203, 39, 61));
        jLabel2.setText("Upload De Prontuário Médico");
        WhitePanel.add(jLabel2);
        jLabel2.setBounds(30, 330, 330, 20);

        jLabel4.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(203, 39, 61));
        jLabel4.setText("Status da Consulta");
        WhitePanel.add(jLabel4);
        jLabel4.setBounds(30, 260, 210, 20);

        jLabel11.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(203, 39, 61));
        jLabel11.setText("Observações");
        WhitePanel.add(jLabel11);
        jLabel11.setBounds(550, 20, 150, 20);

        txtConsObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsObsActionPerformed(evt);
            }
        });
        WhitePanel.add(txtConsObs);
        txtConsObs.setBounds(540, 40, 460, 440);

        jLabel5.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(203, 39, 61));
        jLabel5.setText("Tipo de Consulta");
        WhitePanel.add(jLabel5);
        jLabel5.setBounds(30, 200, 210, 20);

        jButton1.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jButton1.setText("Fazer Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        WhitePanel.add(jButton1);
        jButton1.setBounds(30, 360, 130, 29);

        jButton2.setBackground(new java.awt.Color(203, 39, 61));
        jButton2.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        WhitePanel.add(jButton2);
        jButton2.setBounds(760, 500, 120, 29);

        jButton3.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        WhitePanel.add(jButton3);
        jButton3.setBounds(883, 500, 120, 29);

        jLabel6.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(203, 39, 61));
        jLabel6.setText("Upload De Receita Médica");
        WhitePanel.add(jLabel6);
        jLabel6.setBounds(30, 400, 330, 20);

        jButton4.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jButton4.setText("Fazer Upload");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        WhitePanel.add(jButton4);
        jButton4.setBounds(30, 430, 130, 29);
        WhitePanel.add(fileProntuario);
        fileProntuario.setBounds(450, 450, 70, 70);

        txtConsType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConsTypeFocusGained(evt);
            }
        });
        WhitePanel.add(txtConsType);
        txtConsType.setBounds(20, 220, 460, 30);

        txtConsStatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConsStatusFocusGained(evt);
            }
        });
        WhitePanel.add(txtConsStatus);
        txtConsStatus.setBounds(20, 280, 460, 30);

        jPanel2.add(WhitePanel);
        WhitePanel.setBounds(10, 10, 1060, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WhitePanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_WhitePanelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_WhitePanelFocusGained

    private void txtConsPacientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsPacientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsPacientActionPerformed

    private void txtConsMedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsMedicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsMedicActionPerformed

    private void txtConsObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsObsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsObsActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtConsPacient.disable();
        fileProntuario.hide();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fileProntuario.show();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        optionRegistro optRgstr = new optionRegistro();
        optRgstr.show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        fileProntuario.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: salvar 
        
        int confirm = JOptionPane.showConfirmDialog(null, "Deseja Realmente "
                                                                                    + "Excluir Esse Atendimento?");
        
        if (confirm == JOptionPane.YES_OPTION) {
                Consultas paciente = new Consultas();
                paciente.excluir(txtConsPacient.getText());
                
        optionRegistro optRgstr = new optionRegistro();
        optRgstr.show();
        this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtConsTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConsTypeFocusGained
        // TODO add your handling code here:

        String text = txtConsType.getText();
        if (!text.equalsIgnoreCase("Rotina") && !text.equalsIgnoreCase("Acompanhamento")
            && !text.equalsIgnoreCase("Emergencia" ) && !text.equalsIgnoreCase("Preventiva")
            && !text.equalsIgnoreCase("Especializada") && !text.equalsIgnoreCase("Pre Natal")) {
            String[] options = {"Rotina", "Acompanhamento", "Emergencia", "Preventiva", "Especializada", "Pre Natal"};
            String selectedOption = (String)
            JOptionPane.showInputDialog(registroConsultasExcluir.this, "Selecione um tipo:",
                "Tipo Inválido", JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);

            if (selectedOption != null) {
                txtConsType.setText(selectedOption);
            }

        }
    }//GEN-LAST:event_txtConsTypeFocusGained

    private void txtConsStatusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConsStatusFocusGained
        // TODO add your handling code here:

        String text = txtConsStatus.getText();
        if (!text.equalsIgnoreCase("Agendado") && !text.equalsIgnoreCase("Em andamento")
            && !text.equalsIgnoreCase("Concluído" ) && !text.equalsIgnoreCase("Aguardando Paciente")
            && !text.equalsIgnoreCase("Aguardando Retorno") && !text.equalsIgnoreCase("Cancelado"))

        {

            String[] options = {"Agendado", "Em andamento", "Concluído", "Aguardando Paciente",
                "Aguardando Retorno", "Cancelado"};

            String selectedOption = (String)
            JOptionPane.showInputDialog(registroConsultasExcluir.this, "Selecione um Status:",
                "Status Inválido", JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);

            if (selectedOption != null) {
                txtConsStatus.setText(selectedOption);
            }
        }
    }//GEN-LAST:event_txtConsStatusFocusGained

 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroConsultasExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroConsultasExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroConsultasExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroConsultasExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroConsultasExcluir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WhitePanel;
    private javax.swing.JFileChooser fileProntuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField txtConsData;
    private javax.swing.JTextField txtConsMedic;
    private javax.swing.JTextField txtConsObs;
    private javax.swing.JTextField txtConsPacient;
    private javax.swing.JTextField txtConsStatus;
    private javax.swing.JTextField txtConsType;
    // End of variables declaration//GEN-END:variables

    public void setText(String paciente, String data, String medic, String type, String status, String obs) {
       txtConsPacient.setText(paciente);
       txtConsData.setText(data);
       txtConsMedic.setText(medic);
       txtConsType.setText(type);
       txtConsStatus.setText(status);
       txtConsObs.setText(obs);
       
    }
}
